apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: finance-agent
type: Opaque
data:
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # finanzas
  POSTGRES_DB: ZmluYW56YXM=
